# Define your experiments here. You can use the following as an example:
#
# experiment_name:
#   path:           the path to the Base folder
#   model_name:     name of the anylogic model to connect to
#   config_file:    the excel database file from which to read the config sheets
#   timestep_hours: Float, timestep in hours
#   force_uncached: True | False, force the anylogic model to run in uncached mode
#   show_progress:  True | False, ?
#   parallelize:    True | False, allow the model to run in paralellized mode
#   log_exceptions: True | False, log exceptions or not
#   inputs:         list (optional), list the anylogic input key and the file in
#                   which to find the inputs for each input
#   outcome:        list, name all the outcoems that should be taken from the model.
#                   They become accesible and will be saved under their human_key
#                   Specify if they should be written to a file, or printed out.
#                   Also allows for actions on the data. Currently only normalise is
#                   avaibale.
#

# 300_gridConnections:
#   path: '..'
#   model_name: BaseParTest
#   config_file: input/300_gridConnections/db_backboneConfig_300.xlsx
#   timestep_hours: 0.25
#   force_uncached: false
#   show_progress: false
#   parallelize: true
#   log_exceptions: false
#   inputs:
#     - anylogic_key: P actors config JSON
#       file: config_actors
#       write: True
#     - anylogic_key: P grid connection config JSON
#       file: config_gridConnections
#     - anylogic_key: P grid node config JSON
#       file: config_gridNodes
#     - anylogic_key: P energy assets config JSON
#       file: config_energyAssets
#   outcomes:
#     - anylogic_key: O output runSettings
#       human_key: APIOutputRunData
#       write: True
#       print: True
#     - anylogic_key: O output actorData
#       human_key: APIOutputAgentData
#       write: true
#       print: False
#     # - anylogic_key: O charging profile E vs k W
#     #   human_key: EVChargingProfile
#     #   action: normalise
#     #   write: true
#     #   print: false
#     # - anylogic_key: O output trigger
#     #   human_key: OutputTrigger
#     #   write: false
#     #   print: true

300_gridConnections_27okt:
  path: ".."
  model_name: Base_27okt
  config_file: input/300_gridConnections/db_backboneConfig_300.xlsx
  timestep_hours: 0.25
  force_uncached: false
  show_progress: false
  parallelize: true
  log_exceptions: false
  inputs:
    - anylogic_key: P actors config JSON
      file: config_actors
    - anylogic_key: P grid connection config JSON
      file: config_gridConnections
    - anylogic_key: P grid node config JSON
      file: config_gridNodes
    - anylogic_key: P energy assets config JSON
      file: config_energyAssets
    - anylogic_key: P policies config JSON
      file: config_policies

  outcomes:
    - anylogic_key: O output runSettings
      human_key: APIOutputRunData
      write: True
      print: True
    - anylogic_key: O output actorData
      human_key: APIOutputAgentData
      write: true
      print: False
    # - anylogic_key: O charging profile E vs k W
    #   human_key: EVChargingProfile
    #   action: normalise
    #   write: true
    #   print: false
    # - anylogic_key: O output trigger
    #   human_key: OutputTrigger
    #   write: false
    #   print: true
